### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by lagartoflojo** [satya164/gjs-helpers#1]
Hi,
These helpers are really great, and I'm using them in an extension.
I'd like to publish my extension, but unfortunately there is no license in this repo.
In fact, the extensions.gnome.org site explicitly asks to confirm that "I verify that my extension can be distributed under the terms of the GPLv2+" when you want to upload a new extension.

It would be great if you could add a compatible license! Thanks!

**Comment by satya164** [comment]
@lagartoflojo Hey sorry, didn't notice this earlier. Just added a license.

**Comment by lagartoflojo** [comment]
Excellent news! Thanks a lot :)
